# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-13 00:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=45)),
                ('city_zipcode', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.IntegerField()),
                ('cloudy', models.CharField(max_length=20)),
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='weather.City')),
            ],
        ),
    ]
